"""SVI fit tests: recovering a known smile from synthetic data generated by svi_total_variance itself."""

import numpy as np
import pandas as pd
import pytest

from dpre.calibration.arbitrage import check_butterfly_arbitrage, check_calendar_arbitrage
from dpre.calibration.svi import (
    calibrate_svi_slice,
    calibrate_svi_slice_arbitrage_free,
    calibrate_svi_surface,
    svi_total_variance,
)

TRUE_PARAMS = dict(a=0.04, b=0.15, rho=-0.4, m=0.0, sigma=0.2)
T = 0.5


def test_svi_fit_reprices_smile_within_tolerance() -> None:
    """Fitting to noiseless synthetic SVI data should reprice the total-variance curve almost exactly."""
    k = np.linspace(-0.6, 0.6, 25)
    w_true = svi_total_variance(k, **TRUE_PARAMS)
    weights = np.ones_like(k)

    fitted = calibrate_svi_slice(k, w_true, weights, T)
    w_fitted = svi_total_variance(k, fitted.a, fitted.b, fitted.rho, fitted.m, fitted.sigma)

    assert w_fitted == pytest.approx(w_true, abs=1e-6)


def test_svi_fit_robust_to_noise() -> None:
    """With small quote noise, the fit should still reprice the curve within a loose tolerance."""
    rng = np.random.default_rng(0)
    k = np.linspace(-0.6, 0.6, 25)
    w_true = svi_total_variance(k, **TRUE_PARAMS)
    w_noisy = w_true + rng.normal(scale=1e-4, size=k.shape)
    weights = np.ones_like(k)

    fitted = calibrate_svi_slice(k, w_noisy, weights, T)
    w_fitted = svi_total_variance(k, fitted.a, fitted.b, fitted.rho, fitted.m, fitted.sigma)

    assert w_fitted == pytest.approx(w_true, abs=5e-3)


def test_svi_params_carry_maturity() -> None:
    """Calibrated params record the maturity they were fit on."""
    k = np.linspace(-0.3, 0.3, 10)
    w = svi_total_variance(k, **TRUE_PARAMS)
    fitted = calibrate_svi_slice(k, w, np.ones_like(k), T)
    assert fitted.T == T


def test_calibrate_svi_surface_ignores_deep_wing_outliers() -> None:
    """A couple of noisy deep-wing quotes shouldn't drag the fit off the liquid, near-the-money smile."""
    spot, r, q = 100.0, 0.0, 0.0
    forward = spot * np.exp((r - q) * T)
    k_liquid = np.linspace(-0.3, 0.3, 30)
    strikes_liquid = forward * np.exp(k_liquid)
    iv_liquid = np.sqrt(svi_total_variance(k_liquid, **TRUE_PARAMS) / T)

    strikes_wing = np.array([forward * np.exp(-2.0), forward * np.exp(2.0)])
    iv_wing = np.array([2.5, 2.5])  # implausible, noisy last-price-derived IV far out of the money
    k_all = np.concatenate([k_liquid, [-2.0, 2.0]])

    df = pd.DataFrame(
        {
            "strike": np.concatenate([strikes_liquid, strikes_wing]),
            "implied_vol": np.concatenate([iv_liquid, iv_wing]),
            "option_type": np.where(k_all >= 0, "call", "put"),
            "T": T,
            "bid": 1.0,
            "ask": 1.05,
            "quote_source": "bid_ask",
        }
    )

    [fitted] = calibrate_svi_surface(df, spot, r, q)
    w_fitted = svi_total_variance(k_liquid, fitted.a, fitted.b, fitted.rho, fitted.m, fitted.sigma)
    w_true = svi_total_variance(k_liquid, **TRUE_PARAMS)
    assert w_fitted == pytest.approx(w_true, abs=1e-3)


def test_arbitrage_free_slice_passes_butterfly_check_even_from_bad_data() -> None:
    """Fit against a couple of extreme wing points that used to blow up the unconstrained fit
    (see docs/technical_notes.md sec. 3): the constrained fit must stay butterfly-arbitrage-free."""
    k = np.concatenate([np.linspace(-0.4, 0.4, 20), [-1.4, 1.4]])
    w = np.concatenate([svi_total_variance(np.linspace(-0.4, 0.4, 20), **TRUE_PARAMS), [3.0, 3.0]])
    weights = np.ones_like(k)

    fitted = calibrate_svi_slice_arbitrage_free(k, w, weights, T)

    result = check_butterfly_arbitrage(fitted)
    assert result.arbitrage_free, f"min_g={result.min_g}"


def test_arbitrage_free_calendar_constraint_corrects_conflicting_data() -> None:
    """Two maturities whose raw target data is calendar-*violating* by construction (the longer
    maturity's total variance is deliberately set lower than the shorter one's): the sequential,
    constrained fit must still produce a calendar-arbitrage-free pair of slices."""
    high_level = dict(a=0.05, b=0.30, rho=-0.3, m=0.0, sigma=0.2)
    low_level = dict(a=0.01, b=0.05, rho=-0.2, m=0.0, sigma=0.2)
    T1, T2 = 0.1, 0.3
    k = np.linspace(-0.4, 0.4, 25)
    weights = np.ones_like(k)

    w1 = svi_total_variance(k, **high_level)
    w2 = svi_total_variance(k, **low_level)
    assert np.all(w2 < w1)  # sanity: the raw inputs really do conflict with no-calendar-arbitrage

    slice1 = calibrate_svi_slice_arbitrage_free(k, w1, weights, T1, prev_slice=None)
    slice2 = calibrate_svi_slice_arbitrage_free(k, w2, weights, T2, prev_slice=slice1)

    assert check_butterfly_arbitrage(slice1).arbitrage_free
    assert check_butterfly_arbitrage(slice2).arbitrage_free
    calendar = check_calendar_arbitrage([slice1, slice2], spot=100.0, r=0.0, q=0.0)
    assert calendar.arbitrage_free, calendar.violations


def test_calibrate_svi_surface_end_to_end_is_arbitrage_free() -> None:
    """Full pipeline (grouping, OTM filter, sequential constrained fit) on 3 maturities built from
    deliberately conflicting target data should still yield a fully arbitrage-free surface."""
    spot, r, q = 100.0, 0.0, 0.0
    param_sets = [
        (0.15, dict(a=0.05, b=0.30, rho=-0.3, m=0.0, sigma=0.2)),
        (0.35, dict(a=0.01, b=0.05, rho=-0.2, m=0.0, sigma=0.2)),  # deliberately "too low" for its T
        (0.60, dict(a=0.06, b=0.25, rho=-0.25, m=0.0, sigma=0.2)),
    ]
    frames = []
    for T_, params in param_sets:
        forward = spot * np.exp((r - q) * T_)
        k = np.linspace(-0.4, 0.4, 25)
        strikes = forward * np.exp(k)
        iv = np.sqrt(svi_total_variance(k, **params) / T_)
        frames.append(
            pd.DataFrame(
                {
                    "strike": strikes,
                    "implied_vol": iv,
                    "option_type": np.where(k >= 0, "call", "put"),
                    "T": T_,
                    "bid": 1.0,
                    "ask": 1.05,
                    "quote_source": "bid_ask",
                }
            )
        )
    df = pd.concat(frames, ignore_index=True)

    slices = calibrate_svi_surface(df, spot, r, q)
    assert len(slices) == 3
    for s in slices:
        assert check_butterfly_arbitrage(s).arbitrage_free
    calendar = check_calendar_arbitrage(slices, spot, r, q)
    assert calendar.arbitrage_free, calendar.violations
